### ISSUE TITLE
Crucial Bugfix: missing exclamation mark

### ISSUE THREAD

**Issue by AndreasGB** [JohannesAck/johannesack.github.io#1]
#### Issue description
There is a crucial exclamation mark missing in the webpage.

#### Steps to reproduce the issue

1. Open web browser
2. Navigate to johannesack.github.io
3. Look at text

#### What's the expected result?

- Existing exclamation mark

#### What's the actual result?

- No exclamation mark

#### Screenshot
 ![Screenshot](https://i.imgur.com/ZbsSBEd.png)

**Comment by AndreasGB** [comment]
Developed a hotfix #2

**Comment by vpfautz** [comment]
Realy fast fix, great!

**Comment by JohannesAck** [comment]
Thanks a lot for your contribution, however, I can't accept it in its current condition.

Could you please read the CONTRIBUTING.md and adjust your commit accordingly?

Thanks a lot,
-J

**Comment by AndreasGB** [comment]
Hello J,

I am very sorry that my commit was not up to the required quality.

Sadly, I seem to be unable to locate your contribution guide. Can you please link it for me? 

Kind regards,

-A

**Comment by JohannesAck** [comment]
Hi A,

sure, here [here](https://github.com/JohannesAck/johannesack.github.io/blob/master/contributing.md) you go.

Best,
-J

**Comment by AndreasGB** [comment]
Hi J,

I am sorry but this page 404s for me. Did you maybe miss it when doing your last commit?

Best Wishes,
-A

**Comment by JohannesAck** [comment]
fixed in #3 and #2 , thanks a lot!
